function packageEmbedded()
%PACKAGEEMBEDDED  組み込みターゲット向け C ソース一式を embedded/ に集約する.
%
%   内容:
%     embedded/planner/   計画SCP 1反復のフルC (planIterEmb lib 生成物)
%                         = 線形化+離散化+QP組立+Ruiz+PIPG が単一Cパイプライン
%     embedded/solver/    手書きC++ PIPG コア (追従MPC用ソルバ, 依存ゼロ)
%     embedded/README.md  統合メモ
%
%   依存: 事前に codegenPlanIter を実行して lib 生成物を作っておくこと.
%
%   See also CODEGENPLANITER, CODEGENBUILD, BUILDPIPG
here = fileparts(mfilename('fullpath'));  proj = fileparts(here);
emb = fullfile(proj,'embedded');
if ~exist(emb,'dir'), mkdir(emb); end

%% --- planner: planIterEmb の lib 生成C ---
srcdir = fullfile(here,'codegen_planiter_lib');
if ~exist(srcdir,'dir'), srcdir = fullfile(here,'cpp','codegen_planiter_lib'); end
assert(exist(srcdir,'dir')==7, 'codegenPlanIter を先に実行してください');
pdir = fullfile(emb,'planner');
if ~exist(pdir,'dir'), mkdir(pdir); end
cf = [dir(fullfile(srcdir,'**','*.c')); dir(fullfile(srcdir,'**','*.h'))];
n1 = 0;
for i = 1:numel(cf)
    copyfile(fullfile(cf(i).folder,cf(i).name), fullfile(pdir,cf(i).name));
    n1 = n1 + 1;
end

%% --- solver: 手書きC++ (追従MPC側. mexFunction 部はMATLAB専用と明記) ---
sdir = fullfile(emb,'solver');
if ~exist(sdir,'dir'), mkdir(sdir); end
copyfile(fullfile(here,'cpp','pipg_mex.cpp'), fullfile(sdir,'pipg.cpp'));
copyfile(fullfile(here,'cpp','ruiz_mex.cpp'), fullfile(sdir,'ruiz.cpp'));

%% --- README ---
fid = fopen(fullfile(emb,'README.md'),'w','n','UTF-8');
fprintf(fid, [ ...
'# 組み込みターゲット向け Cソース一式\n\n' ...
'## planner/ — 計画SCPの1反復 (フルC, MATLAB Coder生成)\n\n' ...
'エントリ: `planIterEmb.c` の `planIterEmb(...)`。\n' ...
'1回の呼び出しで 線形化+離散化 -> QP組立(CSC) -> Ruiz -> PIPG -> 復元 を実行。\n' ...
'依存ライブラリなし (BLAS/LAPACK不使用, grep検証済み)。\n' ...
'ウォームスタート: 引数 zWarm に前回の zOut を渡す (構造が変わったら空)。\n' ...
'実測 (デスクトップ): warm 33 ms / cold 315 ms (N=50節点, QP 2414変数)。\n' ...
'RTI運用: 1周期1反復・ウォームスタートで 100 ms 周期に収まる。\n\n' ...
'## solver/ — 手書きC++ PIPG (追従MPC用)\n\n' ...
'`pipg.cpp` の `namespace pipg` がコア (依存ゼロ)。末尾の mexFunction は\n' ...
'MATLAB 検証用なので組み込みでは削除し, pipg::solve を直接呼ぶ。\n' ...
'CSC疎行列 + 対角コストP。固定反復モードで実行時間決定的 (300反復 = 8-19 ms)。\n' ...
'`ruiz.cpp` は Ruiz 平衡化のスケール計算 (同様に mexFunction を除去して使用)。\n\n' ...
'## 未C化 (ホスト側MATLABに残っているもの)\n\n' ...
'- 追従MPCのQP組立 (track6Step 内, ~数ms) — planner と同じ手法で移植可能\n' ...
'- 参照の高密度化 densify6 (再計画受け入れ時のみ, ~10ms)\n\n' ...
'## 検証\n\n' ...
'- 等価性: planIterEmb は buildPlan6+precondition+solveQP と同一反復数・同一解\n' ...
'- pipg.cpp は MATLAB版 solveQP とビット一致 (buildPIPG で再検証可能)\n' ...
]);
fclose(fid);
fprintf('パッケージ完了: %s (planner %dファイル + solver 2ファイル + README)\n', emb, n1);
end
